### PR TITLE
Fix issue 48 reported in the Rin-Editor repository

### PR DESCRIPTION
**Pull request by lairdshaw**
Needs a lot of testing. I am not sure this fix is comprehensive nor bug free.

### CODE REVIEW

**Comment by martec** [comment]
I did some tests here in Edge:

the code like this


and the selection below


result bbcode like below:


This does not occur in all types of selection. Depending on the selection it works correctly.

The below is bbcode of post that i used to made test
```
[list=1]
[*]fsfsdfds
[*]fsfsdfds
[*]fsfsdfds
[/list]

[list]
[*]fdsfdsfs
[*]fdsfdsfs
[*]fdsfdsfs
[/list]

jhggggjgjghhj
[b]gdgdgdfgd[/b]dsfsdfdsf

[quote]fsdfdsfsdf[/quote]
[code]fdsfsdfsd[/code]
[php]fdsfsfds[/php]
[color=#2ECC71]fsdfsdfsd[/color]fdsfsdfs[b][i][u][s]fdsfsdfds[/s][/u][/i][/b]
[quote][align=left]fdsfdsfdss[/align][align=center]fdsfsdfds[/align][align=right]fdsfdsfdsf[/align][/quote]
[hr]
 :dodgy:
```

If the solution to this is difficult, you can dismiss this challenge. I don't want to steal your precious time.
And not to mention that we will probably have to work on the issue of selecting text with color that is also lost when the selection is just text with color.

**Comment by lairdshaw** [comment]
> If the solution to this is difficult, you can dismiss this challenge.

No, it was a worthy challenge. I've tried to rise to it. See whether my improvements work for you or not...

**Comment by martec** [comment]
Hi now tested with new code.... thanks again for effort!

result with new code

Capturar

corret output to 1: dsfsdfdsf (without color, i and b tag)
corret output to 2: fdsfsdfs (without color, i and b tag)

result withou this patch (the desired result)

Capturar2

**Comment by lairdshaw** [comment]
Hmm. I see. It seems that [Selection.containsNode()](https://developer.mozilla.org/en-US/docs/Web/API/Selection/containsNode) doesn't always return what I expect it to return. In your example above, I expect it to return true for the initial span styled bold (the one enclosing the text dgdfdg), but instead it returns false.

I'm tentatively going to say then that this problem can't be solved, but I will be happy if it can.

Feel free to close this PR.

**Comment by lairdshaw** [comment]
I think I've solved the problem after all. If you would be kind enough to test *yet again*, I would be appreciative.

Re the extraneous `color` tags that get added for the default colour, there is not much we can do about that, however [PR 4186](https://github.com/mybb/mybb/pull/4186) in MyBB core, now merged, mostly fixes this. And they are, in any case, harmless.

**Comment by martec** [comment]
Thanks for the effort ... For my tests except the color part is ok.
Perhaps better to disregard the color part. The reason is that with this addition of tag color to default color, when used in a different theme (light and dark theme) it will be quite inconvenient.
I may be being quite rude for asking for the withdrawal of color treatment, but I think it's better without it because it may cause more headache.

**Comment by lairdshaw** [comment]
Understood, however, please consider this:

Rather than removing `color` tags wholesale, we could take a similar approach to the core PR I mentioned above: check whether the colour matches the editor's default colour, and if so, ignore it.

I considered adding that functionality but wanted to run it by you first because it would be editor-dependent, and if I understand correctly, you use this code on a different editor for your Rin-Editor plugin - correct?

**Comment by martec** [comment]
Yes, I use this code for Rin Editor. But you can add the SCEditor default color modification without any problems.
Of course I will have to make changes to make it compatible with Rin Editor or just not to handle the color tag.

**Comment by lairdshaw** [comment]
> But you can add the SCEditor default color modification without any problems.

OK, good, I've now done that.

**Comment by martec** [comment]
Hi thanks again.

I made simple test here modifying the mybb theme background color and the default color of the color font ...
When you do this, it probably differs with the editor's background color and the editor's default font color, and the correction doesn't work in this case. I think this correction should check the default color used within post_content.

**Comment by lairdshaw** [comment]
Let me try to understand:

The editor's foreground (text) `color` is C1, and you've changed the theme's foreground(text) `color` to C2, where C1 and C2 are different colours, even after normalisation.

Now, please tell me what steps you go through to generate text in the editor that you think should have its colour (whether C1 or C2) removed.

**Comment by martec** [comment]
Maybe I was not clear. Simply use a random mybb theme (an example like this https://community.mybb.com/thread-160259.html) that has the font color C1. And this C1 will not necessarily be the same color as the editor font.

**Comment by lairdshaw** [comment]
Right, right. I was confused given the fix I'd made to core code, in which the copy-n-paste occurs wholly _within_ the editor, and thus where the editor's colour is the only relevant one. Understood now. I'll see about fixing the code.

**Comment by martec** [comment]
Sorry, I should have been clearer too.

**Comment by lairdshaw** [comment]
> Sorry, I should have been clearer too.

Not at all; you were perfectly clear.

Please check whether this code works.

**Comment by martec** [comment]
Hi...

Perfect! 
it's great for me. Do you still want to make changes? If not, I will merge it.

**Comment by lairdshaw** [comment]
I reckon so long as it's working as-is, you can go ahead and merge it. Hopefully, now that we're pulling the colour from the post body rather than the editor, you'll be able to use this file as-is for your Rin-Editor plugin too.

And now we're one-up on the XenForo team. :+1:

**Comment by martec** [comment]
Again very thanks...
Yes, now i can use your code in Rin Editor without having to modify it.

>And now we're one-up on the XenForo team. 👍

yes, yes! It was an amazing job. Very grateful!

**Comment by Eldenroot** [comment]
Good job! Thank you

**Comment by lairdshaw** [comment]
It took a few goes but we got there in the end.

**Comment by Eldenroot** [comment]
You use sceditor, right? Why do you prefer it over rin editor? I had been using sceditor for a long time but it was not good... Maybe now it is better than before... I dont knoelw, but I am really happy that @martec is back and continue to maintain rin editor, because latest improvements are great - table support, highlighting text, imgur, ctrl+v directly to posts etc.

Thank you both again, see ya, cheers!

**Comment by lairdshaw** [comment]
> You use sceditor, right?

Yep.

> Why do you prefer it over rin editor?

I guess I'm a little conservative in that way - I tend to stick with the default; that way official support from core is guaranteed and there is less chance of incompatibility, e.g., with plugins that rely on the default editor being present.

But I haven't tried Rin Editor yet, so I can't in that sense say I prefer one or the other. It does sound really good.

**Pull request merged**
